import os
import argparse
import torch
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
from tqdm import tqdm
from omegaconf import OmegaConf

from tsr.system import TSR
from tsr.utils import save_video


def visualize():
    """Visualize 3D models generated by the fine-tuned TripoSR model"""
    parser = argparse.ArgumentParser(description="Visualize TripoSR fine-tuned model outputs")
    parser.add_argument("--config", type=str, default="config.yaml", help="Path to config file")
    parser.add_argument("--model_path", type=str, required=True, help="Path to fine-tuned model checkpoint")
    parser.add_argument("--input_dir", type=str, required=True, help="Directory containing input images")
    parser.add_argument("--output_dir", type=str, default="visualization", help="Output directory")
    parser.add_argument("--device", type=str, default="cuda:0", help="Device to use")
    parser.add_argument("--views", type=int, default=30, help="Number of views to render")
    parser.add_argument("--resolution", type=int, default=256, help="Mesh resolution")
    parser.add_argument("--bake_texture", action="store_true", help="Bake texture atlas for mesh")
    parser.add_argument("--texture_resolution", type=int, default=2048, help="Texture resolution")
    args = parser.parse_args()
    
    # Create output directory
    os.makedirs(args.output_dir, exist_ok=True)
    
    # Set device
    device = args.device
    if not torch.cuda.is_available() and device.startswith("cuda"):
        print("CUDA not available, using CPU instead")
        device = "cpu"
    
    # Load configuration
    config = OmegaConf.load(args.config)
    
    # Initialize model
    print("Loading model...")
    model = TSR(config)
    model.load_state_dict(torch.load(args.model_path, map_location=device))
    model.to(device)
    model.eval()
    
    # Find all image files
    image_files = []
    for root, _, files in os.walk(args.input_dir):
        for file in files:
            if file.lower().endswith(('.png', '.jpg', '.jpeg')):
                image_files.append(os.path.join(root, file))
    
    if not image_files:
        print(f"No image files found in {args.input_dir}")
        return
    
    print(f"Found {len(image_files)} images")
    
    for image_path in tqdm(image_files, desc="Processing images"):
        # Get filename without extension
        filename = os.path.splitext(os.path.basename(image_path))[0]
        
        # Create output subdirectory
        output_subdir = os.path.join(args.output_dir, filename)
        os.makedirs(output_subdir, exist_ok=True)
        
        # Load image
        image = Image.open(image_path).convert("RGB")
        
        # Process image with model
        with torch.no_grad():
            scene_codes = model([image], device=device)
            
            # Render multiple views
            render_images = model.render(
                scene_codes, 
                n_views=args.views, 
                return_type="pil"
            )
            
            # Extract mesh
            meshes = model.extract_mesh(
                scene_codes, 
                has_vertex_color=not args.bake_texture,
                resolution=args.resolution
            )
        
        # Save input image
        image.save(os.path.join(output_subdir, "input.png"))
        
        # Save rendered views as individual images
        for i, render in enumerate(render_images[0]):
            render.save(os.path.join(output_subdir, f"render_{i:03d}.png"))
        
        # Save rendered views as video
        save_video(
            render_images[0], 
            os.path.join(output_subdir, "rotation.mp4"), 
            fps=30
        )
        
        # Save mesh
        mesh_path = os.path.join(output_subdir, "mesh.obj")
        meshes[0].export(mesh_path)
        
        # Create a visualization with input and sample renders
        plt.figure(figsize=(15, 5))
        
        # Input image
        plt.subplot(1, 5, 1)
        plt.imshow(np.array(image))
        plt.title("Input Image")
        plt.axis('off')
        
        # Four rendered views
        view_indices = [0, args.views // 4, args.views // 2, 3 * args.views // 4]
        for i, idx in enumerate(view_indices):
            plt.subplot(1, 5, i + 2)
            plt.imshow(np.array(render_images[0][idx]))
            plt.title(f"View {idx}")
            plt.axis('off')
        
        plt.tight_layout()
        plt.savefig(os.path.join(output_subdir, "preview.png"))
        plt.close()
        
        print(f"Saved results for {filename} to {output_subdir}")


if __name__ == "__main__":
    visualize() 